import { extractPincode, resolveLocation } from './matcher';
import { isWithinTamilNaduBounds, isTamilNaduState } from './bounds';
import { getCachedLocationFromMemory } from './cache-store';
import { normalizeKey } from './tn-locations';

/**
 * List of known out-of-state cities, districts, regions, and states across India.
 * Specifically includes major migration sources / neighboring states (Kerala, Karnataka, AP, North India).
 */
export const OUT_OF_STATE_KEYWORDS = new Set([
  // States
  'kerala',
  'karnataka',
  'andhra pradesh',
  'andhra',
  'telangana',
  'maharashtra',
  'delhi',
  'new delhi',
  'uttar pradesh',
  'rajasthan',
  'gujarat',
  'west bengal',
  'bengal',
  'bihar',
  'punjab',
  'haryana',
  'madhya pradesh',
  'odisha',
  'orissa',
  'assam',
  'goa',
  'jharkhand',
  'chhattisgarh',
  'uttarakhand',
  'himachal',
  'kashmir',

  // Karnataka
  'bangalore',
  'bengaluru',
  'mysore',
  'mysuru',
  'mangalore',
  'mangaluru',
  'hubli',
  'hubballi',
  'belgaum',
  'belagavi',
  'bellary',
  'ballari',
  'davangere',
  'shimoga',
  'shivamogga',
  'tumkur',
  'tumakuru',
  'gulbarga',
  'kalaburagi',
  'bidar',
  'raichur',
  'udupi',
  'kolar',
  'mandya',
  'hassan',
  'chikmagalur',
  'chikkamagaluru',
  'chamarajanagar',

  // Kerala
  'kochi',
  'cochin',
  'ernakulam',
  'kozhikode',
  'calicut',
  'trivandrum',
  'thiruvananthapuram',
  'thrissur',
  'trichur',
  'palakkad',
  'palghat',
  'malappuram',
  'kannur',
  'cannore',
  'kottayam',
  'kollam',
  'quilon',
  'alappuzha',
  'alleppey',
  'kasaragod',
  'kasargod',
  'wayanad',
  'idukki',
  'pathanamthitta',
  'thodupuzha',
  'payyoli',
  'edavanna',
  'tirur',
  'manjeri',
  'perinthalmanna',
  'ponnani',
  'vadanappally',
  'kunnamkulam',
  'chalakudy',
  'kodungallur',
  'guruvayur',
  'irinjallakuda',
  'irinjalakuda',
  'cherthala',
  'kayamkulam',
  'mavelikkara',
  'changanassery',
  'pala',
  'kattappana',
  'adimali',
  'munnar',
  'nedumkandam',
  'sulthan bathery',
  'mananthavady',
  'kalpetta',
  'vadakara',
  'koyilandy',
  'taliparamba',
  'payyanur',
  'kanhangad',
  'nilambur',
  'kondotty',
  'ottapalam',
  'shoranur',
  'chittur',
  'mannarkkad',
  'alathur',
  'pattambi',
  'cherpulassery',
  'attingal',
  'nedumangad',
  'neyyattinkara',
  'varkala',
  'karunagappally',
  'paravur',
  'punalur',
  'adoor',
  'thiruvalla',
  'pandalam',
  'ranai',

  // Andhra Pradesh & Telangana
  'hyderabad',
  'secunderabad',
  'vijayawada',
  'visakhapatnam',
  'vizag',
  'guntur',
  'nellore',
  'kurnool',
  'rajahmundry',
  'kakinada',
  'tirupati',
  'anantapur',
  'kadapa',
  'chittoor',
  'warangal',
  'nizamabad',
  'karimnagar',
  'khammam',
  'eluru',
  'ongole',
  'nandyal',
  'machilipatnam',
  'adoni',
  'tenali',
  'proddatur',
  'hindupur',
  'bhimavaram',
  'madanapalle',
  'guntakal',
  'dharmavaram',
  'gudivada',
  'narasaraopet',
  'tadipatri',
  'tadepalligudem',
  'chilakaluripet',
  'mancherial',
  'ramagundam',
  'suryapet',
  'miryalaguda',
  'siddipet',
  'jagtial',
  'adilabad',

  // Maharashtra
  'mumbai',
  'bombay',
  'pune',
  'nagpur',
  'thane',
  'nashik',
  'aurangabad',
  'solapur',
  'kolhapur',
  'navi mumbai',
  'amravati',
  'sangli',
  'hingoli',
  'nanded',
  'jalgaon',
  'akola',
  'latur',
  'dhule',
  'ahmednagar',
  'chandrapur',
  'parbhani',
  'jalna',
  'beed',
  'gondia',
  'satara',
  'yavatmal',
  'osmanabad',
  'dharashiv',
  'wardha',

  // Kerala Extra Taluks, Municipalities & Towns
  'perumbavoor',
  'kothamangalam',
  'kottakkal',
  'tanur',
  'aluva',
  'muvattupuzha',
  'angamaly',
  'kattapana',
  'vengara',
  'aroor',
  'thalassery',
  'rajakumary',
  'ottappalam',
  'triprayar',
  'chavakkad',
  'cherthala',
  'edapal',
  'valanchery',
  'parappanangadi',
  'north paravur',
  'tripunithura',
  'kalamassery',
  'alwaye',
  'moovattupuzha',
  'piravom',
  'kanjirappally',
  'chengannur',
  'haripad',
  'kozhencherry',
  'ranni',
  'konni',
  'kottarakkara',
  'chathannoor',
  'erumely',
  'koratty',
  'trissur',
  'eranakulam',
  'vatakara',
  'chalakudi',
  'areekode',
  'perintalmanna',
  'palakad',
  'pulamanthole',
  'anchal',
  'sasthamcotta',
  'kottappuram',
  'ettumanoor',
  'tvm',

  // Uttar Pradesh
  'bareilly',
  'aligarh',
  'ballia',
  'gorakhpur',
  'amroha',
  'azamgarh',
  'saharanpur',
  'moradabad',
  'fatehpur',
  'pilibhit',
  'farrukhabad',
  'jhansi',
  'muzaffarnagar',
  'mathura',
  'rampur',
  'shahjahanpur',
  'firozabad',
  'mainpuri',
  'etawah',
  'etawaha',
  'bulandshahr',
  'hapur',
  'sambhal',
  'budaun',
  'kasganj',
  'hathras',
  'baghpat',
  'shamli',
  'bijnor',
  'lalitpur',
  'jalaun',
  'hamirpur',
  'mahoba',
  'banda',
  'chitrakoot',
  'ayodhya',
  'faizabad',
  'barabanki',
  'sultanpur',
  'amethi',
  'ambedkar nagar',
  'bahraich',
  'shravasti',
  'balrampur',
  'gonda',
  'siddharthnagar',
  'basti',
  'sant kabir nagar',
  'maharajganj',
  'kushinagar',
  'deoria',
  'mau',
  'ghazipur',
  'chandauli',
  'jaunpur',
  'mirzapur',
  'sonbhadra',
  'bhadohi',
  'kaushambi',
  'pratapgarh',
  'unnao',
  'rae bareli',
  'sitapur',
  'hardoi',
  'lakhimpur',
  'orai',
  'padrauna',

  // Madhya Pradesh
  'chhatarpur',
  'sagar',
  'gwalior',
  'ratlam',
  'morena',
  'shivpuri',
  'bhind',
  'sheopur',
  'guna',
  'ashoknagar',
  'datia',
  'ujjain',
  'dewas',
  'shajapur',
  'agar malwa',
  'mandsaur',
  'neemuch',
  'dhar',
  'khargone',
  'barwani',
  'khandwa',
  'burhanpur',
  'alirajpur',
  'jhabua',
  'sehore',
  'raisen',
  'vidisha',
  'rajgarh',
  'betul',
  'hoshangabad',
  'narmadapuram',
  'harda',
  'damoh',
  'panna',
  'tikamgarh',
  'niwari',
  'rewa',
  'satna',
  'sidhi',
  'singrauli',
  'shahdol',
  'anuppur',
  'umaria',
  'jabalpur',
  'katni',
  'dindori',
  'mandla',
  'seoni',
  'chhindwara',
  'balaghat',
  'narsinghpur',

  // Rajasthan
  'jodhpur',
  'kota',
  'ajmer',
  'bikaner',
  'churu',
  'udaipur',
  'alwar',
  'bharatpur',
  'sikar',
  'pali',
  'ganganagar',
  'bhilwara',
  'jhunjhunu',
  'nagaur',
  'chittorgarh',
  'tonk',
  'hanumangarh',
  'beawar',
  'dholpur',
  'sawai madhopur',
  'dungarpur',
  'banswara',
  'rajsamand',
  'sirohi',
  'jalore',
  'barmer',
  'jaisalmer',
  'dausa',
  'karauli',
  'baran',
  'bundi',
  'jhalawar',

  // Gujarat
  'patan',
  'anand',
  'navsari',
  'morbi',
  'surendranagar',
  'bharuch',
  'mehsana',
  'bhuj',
  'porbandar',
  'palanpur',
  'valsad',
  'vapi',
  'gandhidham',
  'gandhinagar',
  'junagadh',
  'jamnagar',
  'bhavnagar',
  'amreli',
  'botad',
  'dahod',
  'godhra',
  'himatnagar',
  'modasa',
  'veraval',
  'gujrat',

  // Bihar & Jharkhand
  'gaya',
  'bhagalpur',
  'muzaffarpur',
  'purnia',
  'darbhanga',
  'bihar sharif',
  'arrah',
  'begusarai',
  'katihar',
  'munger',
  'chhapra',
  'bettiah',
  'saharsa',
  'sasaram',
  'hajipur',
  'dehri',
  'siwan',
  'motihari',
  'nawada',
  'bagaha',
  'buxar',
  'kishanganj',
  'sitamarhi',
  'jamui',
  'jehanabad',
  'dhanbad',
  'bokaro',
  'deoghar',
  'hazaribagh',
  'giridih',
  'ramgarh',
  'medininagar',
  'chirkunda',
  'garhwa',
  'chatra',

  // West Bengal & Odisha
  'howrah',
  'asansol',
  'siliguri',
  'durgapur',
  'bardhaman',
  'malda',
  'baharampur',
  'habra',
  'kharagpur',
  'shantipur',
  'dankuni',
  'dhulian',
  'ranaghat',
  'haldia',
  'raiganj',
  'krishnanagar',
  'nabadwip',
  'midnapore',
  'jalpaiguri',
  'balurghat',
  'basirhat',
  'bankura',
  'chakdaha',
  'darjeeling',
  'alipurduar',
  'purulia',
  'murshidabad',
  'rourkela',
  'brahmapur',
  'sambalpur',
  'puri',
  'balasore',
  'bhadrak',
  'baripada',
  'jharsuguda',
  'jeypore',
  'dhenkanal',
  'jajpur',

  // Assam & North East
  'nagaon',
  'jorhat',
  'gauhati',
  'guwahati',
  'silchar',
  'dibrugarh',
  'tezpur',
  'tinsukia',
  'bongaigaon',
  'dhubri',
  'diphu',
  'north lakhimpur',
  'karimganj',
  'sivasagar',
  'goalpara',
  'barpeta',
  'shillong',
  'imphal',
  'agartala',
  'aizawl',
  'kohima',
  'itanagar',
  'gangtok',

  // Punjab & Haryana
  'bathinda',
  'hoshiarpur',
  'batala',
  'moga',
  'abohar',
  'pathankot',
  'malerkotla',
  'khanna',
  'muktsar',
  'barnala',
  'firozpur',
  'kapurthala',
  'panipat',
  'ambala',
  'yamunanagar',
  'rohtak',
  'hisar',
  'karnal',
  'sonipat',
  'panchkula',
  'bhiwani',
  'sirsa',
  'bahadurgarh',
  'jind',
  'thanesar',
  'kaithal',
  'rewari',
  'palwal',

  // Chhattisgarh & J&K
  'bilaspur',
  'korba',
  'durg',
  'bhilai',
  'rajnandgaon',
  'raigarh',
  'jagdalpur',
  'ambikapur',
  'bemetara',
  'udhampur',

  // Karnataka Extra
  'hosapete',
  'hospete',
  'gadag',
  'koppal',
  'yadgir',
  'chikkaballapur',
  'ramanagara',
  'sirsi',
  'karwar',
  'bhatkal',
  'dandeli',
  'ranibennur',
  'harihar',
  'sindhanur',
  'gangavati',
  'ilkal',
  'shahabad',
  'gokak',
  'sindagi',
  'chikodi',
  'nipani',
  'mudhol',
  'jamkhandi',
  'basavakalyan',
  'sira',
  'davanagere',
  'chamarajanagara',

  // International
  'london',
  'dubai',
  'singapore',
  'kuwait',
  'qatar',
  'doha',
  'riyadh',
  'abu dhabi',
  'sharjah',
  'muscat',
  'oman',
  'bahrain',
  'malaysia',
  'toronto',
  'sydney',
  'dammam',

  // Other Major Indian Metros & Cities
  'kolkata',
  'calcutta',
  'jaipur',
  'lucknow',
  'kanpur',
  'patna',
  'ahmedabad',
  'surat',
  'vadodara',
  'baroda',
  'rajkot',
  'bhopal',
  'indore',
  'chandigarh',
  'ludhiana',
  'amritsar',
  'agra',
  'varanasi',
  'prayagraj',
  'allahabad',
  'meerut',
  'noida',
  'greater noida',
  'gurgaon',
  'gurugram',
  'ghaziabad',
  'faridabad',
  'bhubaneswar',
  'cuttack',
  'ranchi',
  'jamshedpur',
  'raipur',
  'guwahati',
  'dehradun',
  'shimla',
  'srinagar',
  'jammu',
]);

const OUT_OF_STATE_ABBRS = new Set([
  'up', 'mp', 'ap', 'wb', 'kl', 'ka', 'mh', 'gj', 'rj', 'hr', 'pb', 'dl', 'ts', 'uk', 'hp', 'jk'
]);

/**
 * Checks whether a given location query or city name is outside Tamil Nadu.
 * Uses:
 * 1. 6-digit Pincode analysis (out-of-state pincodes)
 * 2. Local Tamil Nadu dictionary matching (never classifies known TN towns as outside)
 * 3. Pre-indexed out-of-state cities/states keywords
 * 4. In-memory LocationCache lookup with GPS bounding box + state validation
 */
export function isLocationOutsideTamilNadu(city: string | null | undefined): boolean {
  if (!city || !city.trim()) {
    // If no city is specified, the lead is not confirmed outside Tamil Nadu
    return false;
  }

  const query = city.trim();
  const lowerQuery = query.toLowerCase();

  // If query is a generic placeholder or junk value, keep as inside TN campaign
  if (/^(city|n\/?a|null|nil|none|test|yes|no|\.|\-)$/i.test(lowerQuery)) {
    return false;
  }
  if (lowerQuery.length <= 2 && !OUT_OF_STATE_ABBRS.has(lowerQuery)) {
    return false;
  }

  // 1. Check out-of-state postal code
  const pinCheck = extractPincode(query);
  if (pinCheck.isOutOfStatePincode) {
    return true;
  }

  // 2. Local Tamil Nadu dictionary check:
  // If matched locally inside TN dictionary, it is guaranteed to be in Tamil Nadu!
  const locMatch = resolveLocation(query);
  if (locMatch.isOutOfState) {
    return true;
  }
  if (locMatch.matched) {
    return false;
  }

  // Non-Tamil Indic script check:
  // Locations written in Malayalam (Kerala), Telugu (AP/TS), Kannada (Karnataka),
  // Gujarati, Odia, Gurmukhi (Punjab), Bengali, or Devanagari (Hindi) that didn't match TN dictionary
  if (/[\u0D00-\u0D7F\u0C00-\u0C7F\u0C80-\u0CFF\u0A80-\u0AFF\u0B00-\u0B7F\u0A00-\u0A7F\u0980-\u09FF\u0900-\u097F]/.test(query)) {
    return true;
  }

  // 3. Direct match against out-of-state keywords
  const normKey = normalizeKey(query);
  if (OUT_OF_STATE_KEYWORDS.has(normKey) || OUT_OF_STATE_KEYWORDS.has(lowerQuery)) {
    return true;
  }

  // Check state abbreviations (e.g. 'up', 'mp')
  if (OUT_OF_STATE_ABBRS.has(lowerQuery)) {
    return true;
  }

  // Check individual words in location string (e.g. "Edavanna Malappuram", "Bangalore North", "Thrissur Kerala")
  const tokens = lowerQuery.split(/[\s,./\\-_()]+/).filter((t) => t.length >= 2);
  for (const t of tokens) {
    const tNorm = normalizeKey(t);
    if (OUT_OF_STATE_KEYWORDS.has(t) || OUT_OF_STATE_KEYWORDS.has(tNorm) || OUT_OF_STATE_ABBRS.has(t)) {
      return true;
    }
  }

  // 4. In-memory LocationCache check (bounding rectangle and state check)
  const cached = getCachedLocationFromMemory(normKey) || getCachedLocationFromMemory(normalizeKey(lowerQuery));
  if (cached) {
    if (cached.state) {
      if (!isTamilNaduState(cached.state)) {
        return true;
      }
      return false;
    }
    if (typeof cached.latitude === 'number' && typeof cached.longitude === 'number' && (cached.latitude !== 0 || cached.longitude !== 0)) {
      const withinBounds = isWithinTamilNaduBounds(cached.latitude, cached.longitude);
      return !withinBounds;
    }
    if (cached.isTamilNadu !== undefined) {
      return !cached.isTamilNadu;
    }
  }

  // Default: if not confirmed outside, keep as inside Tamil Nadu
  return false;
}
